GET http://localhost:1998

###

POST http://localhost:1998
Content-Type: application/json

{
  "firstName": "keren",
  "lastName":"hailu"
}


###
POST http://localhost:1998/register
Content-Type: application/json

{
    "firstName": "eee",
    "lastName": "hhh",
    "email": "kk@",
    "password": "123",
    "lastLogIn": false,
    "isLogIn": true,
    "isAdmin": false
  }
###
PUT http://localhost:1998
Content-Type: application/json

{
  "firstName": "keren",
  "lastName":"hailu",
  "email":"keren@"
}
###
DELETE http://localhost:1998
Content-Type: application/json
